server:
  port: 7000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze5ii45y6qp8r322wo.mysql.rds.aliyuncs.com:3306/yf_all?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: yf_all
    password: yf_all_0123

mybatis:
  mapper-locations: classpath:/mapper/*
